POST http://localhost:8080/auth/login
Content-Type: "application/json"

{
    "username": "test_id",
    "password": "password"
}

###

GET http://localhost:8080/oauth/authorize?response_type=code&client_id=test_client&state=k3VADnxT2ScEz16VqDawrDSjHUG2WqcALiZSSCEpgAN&code_challenge=efe_rqmpENryXVEZv63WKXAg4p6YJUiDJoZJBu8JuVE=&code_challenge_method=S256

###

POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic test_client password

grant_type = authorization_code &
code = 041d98db-4a1f-4712-9d59-e3e869977865 &
redirect_uri = http://localhost:8081 &
code_verifier = IAouJo2w1U8DnurVA5dgfqP5WZ5KLCMdiaeY89ZNum2

###

POST http://localhost:8080/oauth/token/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic test_client password

token=4ae6cc60-0cc4-4879-b5c1-885934ffc357&token_type_hint=access_token