POST http://localhost:8080/auth/login
Content-Type: "application/json"

{
    "username": "test_id",
    "password": "password"
}

###

GET http://localhost:8080/oauth/auth/authorize?response_type=code&client_id=test_client&state=k3VADnxT2ScEz16VqDawrDSjHUG2WqcALiZSSCEpgAN&code_challenge=efe_rqmpENryXVEZv63WKXAg4p6YJUiDJoZJBu8JuVE=&code_challenge_method=S256

###

POST http://localhost:8080/oauth/auth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic test_client password

grant_type = authorization_code &
code = 41941fbb-e584-451d-9cb0-602bb1cb365b &
redirect_uri = http://localhost:8081 &
code_verifier = IAouJo2w1U8DnurVA5dgfqP5WZ5KLCMdiaeY89ZNum2

###

POST http://localhost:8080/oauth/auth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic test_client password

grant_type=password &
username=test_id &
password=password &
scope=read write

####

POST http://localhost:8080/oauth/auth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic test_client password

grant_type=refresh_token&
refresh_token=6a257edf-5a35-4fe8-9130-57608e999d93

###

POST http://localhost:8080/oauth/auth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic test_client password

grant_type=client_credentials

###

POST http://localhost:8080/oauth/auth/token/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic test_client password

token=722f4e31-5661-4943-8954-f608a0646481&token_type_hint=access_token

###